esphome:
  name: ambient
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: light
  manual_ip:
    static_ip: !secret static_ip
    gateway: !secret gateway
    subnet: 255.255.255.0

# Enable logging
logger:

ota:

# Enable Home Assistant API
api:

i2c:
  sda: D1
  scl: D2
  scan: True
  id: bus_a

sensor:
  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    measurement_time: 69
    update_interval: 60s
